// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_func
List my_func();
RcppExport SEXP _zap_rgmoe_my_func() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(my_func());
    return rcpp_result_gen;
END_RCPP
}
// all
LogicalVector all(LogicalVector b);
RcppExport SEXP _zap_rgmoe_all(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(all(b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_zap_rgmoe_my_func", (DL_FUNC) &_zap_rgmoe_my_func, 0},
    {"_zap_rgmoe_all", (DL_FUNC) &_zap_rgmoe_all, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_zap_rgmoe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
