# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_func <- function() {
    .Call(`_zap_rgmoe_my_func`)
}

all <- function(b) {
    .Call(`_zap_rgmoe_all`, b)
}

