# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_masked_moments <- function(zs, pi, mu, sigma) {
    .Call(`_zap_rgmoe_cpp_masked_moments`, zs, pi, mu, sigma)
}

cpp_unmasked_moments <- function(z, pi, mu, sigma) {
    .Call(`_zap_rgmoe_cpp_unmasked_moments`, z, pi, mu, sigma)
}

cpp_EM_Estep <- function(Zs, is_masked, X_f, w_f, beta_f, sigma2) {
    .Call(`_zap_rgmoe_cpp_EM_Estep`, Zs, is_masked, X_f, w_f, beta_f, sigma2)
}

cpp_beta_update <- function(X_f, D0, D1, D2, beta_f, sigma2, lambda) {
    .Call(`_zap_rgmoe_cpp_beta_update`, X_f, D0, D1, D2, beta_f, sigma2, lambda)
}

cpp_beta_marginal_CD <- function(X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak) {
    .Call(`_zap_rgmoe_cpp_beta_marginal_CD`, X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak)
}

cpp_obj_expert <- function(X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak) {
    .Call(`_zap_rgmoe_cpp_obj_expert`, X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak)
}

cpp_sigma2_update <- function(X_f, D0, D1, D2, beta_f) {
    .Call(`_zap_rgmoe_cpp_sigma2_update`, X_f, D0, D1, D2, beta_f)
}

cpp_gating_update <- function(X_f, tau, w_f, gamma, use_proximal_newton = FALSE) {
    .Call(`_zap_rgmoe_cpp_gating_update`, X_f, tau, w_f, gamma, use_proximal_newton)
}

cpp_weight_marginal_CD <- function(Y, X_f, tau, wk_f, gammak) {
    .Call(`_zap_rgmoe_cpp_weight_marginal_CD`, Y, X_f, tau, wk_f, gammak)
}

cpp_obj_gating <- function(Y, X_f, tau, wk_f, gammak) {
    .Call(`_zap_rgmoe_cpp_obj_gating`, Y, X_f, tau, wk_f, gammak)
}

cpp_Fs <- function(X_f, tau, w_f, gamma) {
    .Call(`_zap_rgmoe_cpp_Fs`, X_f, tau, w_f, gamma)
}

cpp_pi_matrix <- function(X_f, w_f) {
    .Call(`_zap_rgmoe_cpp_pi_matrix`, X_f, w_f)
}

cpp_SoTh <- function(x, lambda) {
    .Call(`_zap_rgmoe_cpp_SoTh`, x, lambda)
}

