# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_masked_moments <- function(zs, pi, mu, sigma) {
    .Call(`_zap_rgmoe_cpp_masked_moments`, zs, pi, mu, sigma)
}

cpp_unmasked_moments <- function(z, pi, mu, sigma) {
    .Call(`_zap_rgmoe_cpp_unmasked_moments`, z, pi, mu, sigma)
}

cpp_EM_Estep <- function(Zs, is_masked, X_f, w_f, beta_f, sigma2) {
    .Call(`_zap_rgmoe_cpp_EM_Estep`, Zs, is_masked, X_f, w_f, beta_f, sigma2)
}

cpp_beta_update <- function(X_f, D0, D1, D2, beta_f, sigma2, lambda) {
    .Call(`_zap_rgmoe_cpp_beta_update`, X_f, D0, D1, D2, beta_f, sigma2, lambda)
}

cpp_beta_CoorLQk <- function(X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak) {
    .Call(`_zap_rgmoe_cpp_beta_CoorLQk`, X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak)
}

cpp_obj_expert <- function(X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak) {
    .Call(`_zap_rgmoe_cpp_obj_expert`, X_f, D0k, D1k, D2k, betak_f, sigma2k, lambdak)
}

cpp_sigma2_update <- function(X_f, D0, D1, D2, beta_f) {
    .Call(`_zap_rgmoe_cpp_sigma2_update`, X_f, D0, D1, D2, beta_f)
}

cpp_CoorGateP <- function(X_f, w_f, tau, gamma, rho) {
    .Call(`_zap_rgmoe_cpp_CoorGateP`, X_f, w_f, tau, gamma, rho)
}

cpp_CoorGateP1 <- function(X_f, w_f, tau, gamma, rho) {
    .Call(`_zap_rgmoe_cpp_CoorGateP1`, X_f, w_f, tau, gamma, rho)
}

cpp_CoorLQk <- function(X_f, Y, tau, wk_f, gammak, rho) {
    .Call(`_zap_rgmoe_cpp_CoorLQk`, X_f, Y, tau, wk_f, gammak, rho)
}

cpp_obj_gating <- function(tau, X_f, Y, wk_f, gammak, rho) {
    .Call(`_zap_rgmoe_cpp_obj_gating`, tau, X_f, Y, wk_f, gammak, rho)
}

cpp_Fs <- function(X_f, tau, w_f, gamma, rho) {
    .Call(`_zap_rgmoe_cpp_Fs`, X_f, tau, w_f, gamma, rho)
}

cpp_pi_matrix <- function(X_f, w_f) {
    .Call(`_zap_rgmoe_cpp_pi_matrix`, X_f, w_f)
}

cpp_soth <- function(x, lambda) {
    .Call(`_zap_rgmoe_cpp_soth`, x, lambda)
}

